import { Crop } from './types';

export const CROPS_DATA: Crop[] = [
  // GRAINS & PULSES
  {
    id: '1',
    name: 'Rice (धान)',
    scientificName: 'Oryza sativa',
    category: 'Grains & Pulses',
    profitStatus: 'High',
    latestPrice: 28,
    acresPlanted: 1250,
    season: 'Kharif',
    idealSoilType: 'Clay',
    idealTempRange: { min: 20, max: 35 },
    harvestTime: '4-6 months',
    harvestDays: 120,
    averageYieldPerAcre: 25,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 20, max: 35, optimal: 25 },
      rainfall: { min: 1000, max: 2000, optimal: 1500 },
      humidity: 70,
      phLevel: { min: 5.5, max: 7.0 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Brown Plant Hopper', 'Stem Borer', 'Leaf Folder'],
    commonDiseases: ['Blast', 'Bacterial Leaf Blight', 'Sheath Blight'],
    marketTrends: 'Stable demand with government support price. Export opportunities available.',
    profitPotential: 'High profit margins due to consistent demand and MSP support.',
    plantingTips: ['Prepare seedbed properly', 'Use certified seeds', 'Maintain proper water level'],
    nutritionalValue: 'Rich in carbohydrates, provides energy',
    storageRequirements: 'Cool, dry place with 12-14% moisture content',
    processingUses: ['Rice flour', 'Rice bran oil', 'Rice wine'],
    yearlyData: [
      { year: 2021, acresPlanted: 1100, profitLoss: 15000, averagePrice: 25 },
      { year: 2022, acresPlanted: 1180, profitLoss: 18000, averagePrice: 26 },
      { year: 2023, acresPlanted: 1220, profitLoss: 22000, averagePrice: 27 },
      { year: 2024, acresPlanted: 1250, profitLoss: 25000, averagePrice: 28 },
    ],
    description: 'India\'s staple food crop with strong government support and consistent market demand.'
  },
  {
    id: '2',
    name: 'Wheat (गेहूं)',
    scientificName: 'Triticum aestivum',
    category: 'Grains & Pulses',
    profitStatus: 'Moderate',
    latestPrice: 23,
    acresPlanted: 980,
    season: 'Rabi',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 10, max: 25 },
    harvestTime: '4-5 months',
    harvestDays: 130,
    averageYieldPerAcre: 18,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 10, max: 25, optimal: 20 },
      rainfall: { min: 300, max: 800, optimal: 500 },
      humidity: 50,
      phLevel: { min: 6.0, max: 7.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Aphids', 'Termites', 'Army Worm'],
    commonDiseases: ['Rust', 'Smut', 'Powdery Mildew'],
    marketTrends: 'Steady demand but facing price volatility due to global markets.',
    profitPotential: 'Moderate returns with opportunity for value addition through processing.',
    plantingTips: ['Sow at optimal time', 'Use balanced fertilizers', 'Ensure proper drainage'],
    nutritionalValue: 'High in protein, carbohydrates, and B vitamins',
    storageRequirements: 'Dry storage with 12% moisture content',
    processingUses: ['Flour', 'Semolina', 'Pasta'],
    yearlyData: [
      { year: 2021, acresPlanted: 950, profitLoss: 12000, averagePrice: 20 },
      { year: 2022, acresPlanted: 970, profitLoss: 14000, averagePrice: 21 },
      { year: 2023, acresPlanted: 985, profitLoss: 16000, averagePrice: 22 },
      { year: 2024, acresPlanted: 980, profitLoss: 18000, averagePrice: 23 },
    ]
  },
  {
    id: '3',
    name: 'Maize (मक्का)',
    scientificName: 'Zea mays',
    category: 'Grains & Pulses',
    profitStatus: 'High',
    latestPrice: 19,
    acresPlanted: 720,
    season: 'Kharif',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 15, max: 30 },
    harvestTime: '3-4 months',
    harvestDays: 90,
    averageYieldPerAcre: 22,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 15, max: 30, optimal: 25 },
      rainfall: { min: 500, max: 1200, optimal: 800 },
      humidity: 60,
      phLevel: { min: 5.8, max: 7.0 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Fall Army Worm', 'Stem Borer', 'Shoot Fly'],
    commonDiseases: ['Downy Mildew', 'Rust', 'Leaf Blight'],
    marketTrends: 'Growing demand from poultry and food processing industries.',
    profitPotential: 'Good returns with multiple harvest opportunities.',
    plantingTips: ['Plant with onset of monsoon', 'Maintain plant spacing', 'Apply organic manure'],
    nutritionalValue: 'Rich in carbohydrates, protein, and vitamins',
    storageRequirements: 'Dry storage, protect from pests',
    processingUses: ['Corn oil', 'Corn starch', 'Popcorn', 'Animal feed'],
    yearlyData: [
      { year: 2021, acresPlanted: 680, profitLoss: 8000, averagePrice: 16 },
      { year: 2022, acresPlanted: 700, profitLoss: 10000, averagePrice: 17 },
      { year: 2023, acresPlanted: 710, profitLoss: 12000, averagePrice: 18 },
      { year: 2024, acresPlanted: 720, profitLoss: 14000, averagePrice: 19 },
    ]
  },
  {
    id: '4',
    name: 'Pearl Millet (बाजरा)',
    scientificName: 'Pennisetum glaucum',
    category: 'Grains & Pulses',
    profitStatus: 'Moderate',
    latestPrice: 24,
    acresPlanted: 320,
    season: 'Kharif',
    idealSoilType: 'Sandy',
    idealTempRange: { min: 25, max: 35 },
    harvestTime: '3-4 months',
    harvestDays: 85,
    averageYieldPerAcre: 8,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 25, max: 35, optimal: 30 },
      rainfall: { min: 200, max: 600, optimal: 400 },
      humidity: 50,
      phLevel: { min: 6.0, max: 8.0 }
    },
    pestDiseaseRisk: 'Low',
    commonPests: ['Shoot Fly', 'Stem Borer', 'Hairy Caterpillar'],
    commonDiseases: ['Downy Mildew', 'Rust', 'Ergot'],
    marketTrends: 'Increasing demand for drought-resistant crops and health foods.',
    profitPotential: 'Good returns in arid regions with low input costs.',
    plantingTips: ['Drought tolerant', 'Suitable for marginal lands', 'Mixed cropping beneficial'],
    nutritionalValue: 'High in iron, protein, and fiber',
    storageRequirements: 'Dry storage with proper ventilation',
    processingUses: ['Flour', 'Porridge', 'Health foods'],
    yearlyData: [
      { year: 2021, acresPlanted: 290, profitLoss: 8000, averagePrice: 20 },
      { year: 2022, acresPlanted: 300, profitLoss: 10000, averagePrice: 22 },
      { year: 2023, acresPlanted: 310, profitLoss: 12000, averagePrice: 23 },
      { year: 2024, acresPlanted: 320, profitLoss: 14000, averagePrice: 24 },
    ]
  },

  // VEGETABLES
  {
    id: '5',
    name: 'Tomato (टमाटर)',
    scientificName: 'Solanum lycopersicum',
    category: 'Vegetables',
    profitStatus: 'Moderate',
    latestPrice: 25,
    acresPlanted: 190,
    season: 'Year-round',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 18, max: 27 },
    harvestTime: '3-4 months',
    harvestDays: 90,
    averageYieldPerAcre: 200,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 18, max: 27, optimal: 24 },
      rainfall: { min: 600, max: 1200, optimal: 800 },
      humidity: 60,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'High',
    commonPests: ['Whitefly', 'Fruit Borer', 'Aphids'],
    commonDiseases: ['Early Blight', 'Late Blight', 'Bacterial Wilt'],
    marketTrends: 'High demand but price volatility due to perishable nature.',
    profitPotential: 'Good returns with proper market timing and storage.',
    plantingTips: ['Use disease-resistant varieties', 'Provide support stakes', 'Regular pruning'],
    nutritionalValue: 'Rich in Vitamin C, lycopene, and antioxidants',
    storageRequirements: 'Cool storage at 10-12°C',
    processingUses: ['Ketchup', 'Puree', 'Sauce', 'Dehydrated products'],
    yearlyData: [
      { year: 2021, acresPlanted: 220, profitLoss: 5000, averagePrice: 22 },
      { year: 2022, acresPlanted: 210, profitLoss: 8000, averagePrice: 23 },
      { year: 2023, acresPlanted: 200, profitLoss: 12000, averagePrice: 24 },
      { year: 2024, acresPlanted: 190, profitLoss: 15000, averagePrice: 25 },
    ]
  },
  {
    id: '6',
    name: 'Potato (आलू)',
    scientificName: 'Solanum tuberosum',
    category: 'Vegetables',
    profitStatus: 'High',
    latestPrice: 15,
    acresPlanted: 340,
    season: 'Rabi',
    idealSoilType: 'Sandy',
    idealTempRange: { min: 15, max: 20 },
    harvestTime: '3-4 months',
    harvestDays: 90,
    averageYieldPerAcre: 150,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 15, max: 20, optimal: 18 },
      rainfall: { min: 500, max: 800, optimal: 600 },
      humidity: 80,
      phLevel: { min: 5.0, max: 6.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Potato Tuber Moth', 'Aphids', 'Cutworm'],
    commonDiseases: ['Late Blight', 'Early Blight', 'Black Scurf'],
    marketTrends: 'High demand year-round with processing industry growth.',
    profitPotential: 'Excellent profits with proper storage and timing.',
    plantingTips: ['Use certified seed potatoes', 'Ensure proper earthing up', 'Regular irrigation'],
    nutritionalValue: 'Good source of carbohydrates, vitamin C, and potassium',
    storageRequirements: 'Cool, dark, well-ventilated storage',
    processingUses: ['Chips', 'French fries', 'Starch', 'Dehydrated products'],
    yearlyData: [
      { year: 2021, acresPlanted: 300, profitLoss: 18000, averagePrice: 12 },
      { year: 2022, acresPlanted: 320, profitLoss: 20000, averagePrice: 13 },
      { year: 2023, acresPlanted: 330, profitLoss: 22000, averagePrice: 14 },
      { year: 2024, acresPlanted: 340, profitLoss: 24000, averagePrice: 15 },
    ]
  },
  {
    id: '7',
    name: 'Onion (प्याज)',
    scientificName: 'Allium cepa',
    category: 'Vegetables',
    profitStatus: 'Moderate',
    latestPrice: 22,
    acresPlanted: 280,
    season: 'Rabi',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 12, max: 25 },
    harvestTime: '4-5 months',
    harvestDays: 120,
    averageYieldPerAcre: 120,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 12, max: 25, optimal: 20 },
      rainfall: { min: 600, max: 1000, optimal: 800 },
      humidity: 70,
      phLevel: { min: 6.0, max: 7.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Thrips', 'Onion Maggot', 'Cutworm'],
    commonDiseases: ['Purple Blotch', 'Downy Mildew', 'Basal Rot'],
    marketTrends: 'Price volatility but consistent demand across India.',
    profitPotential: 'Good returns with proper market timing and storage.',
    plantingTips: ['Use quality transplants', 'Maintain proper spacing', 'Avoid waterlogging'],
    nutritionalValue: 'Rich in antioxidants, vitamin C, and sulfur compounds',
    storageRequirements: 'Dry, well-ventilated storage',
    processingUses: ['Dehydrated onion', 'Onion powder', 'Pickles'],
    yearlyData: [
      { year: 2021, acresPlanted: 250, profitLoss: 12000, averagePrice: 18 },
      { year: 2022, acresPlanted: 260, profitLoss: 14000, averagePrice: 19 },
      { year: 2023, acresPlanted: 270, profitLoss: 16000, averagePrice: 20 },
      { year: 2024, acresPlanted: 280, profitLoss: 18000, averagePrice: 22 },
    ]
  },
  {
    id: '8',
    name: 'Brinjal (बैंगन)',
    scientificName: 'Solanum melongena',
    category: 'Vegetables',
    profitStatus: 'High',
    latestPrice: 18,
    acresPlanted: 165,
    season: 'Year-round',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 20, max: 30 },
    harvestTime: '4-5 months',
    harvestDays: 120,
    averageYieldPerAcre: 180,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 20, max: 30, optimal: 25 },
      rainfall: { min: 600, max: 1000, optimal: 800 },
      humidity: 65,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'High',
    commonPests: ['Fruit Borer', 'Aphids', 'Jassids'],
    commonDiseases: ['Bacterial Wilt', 'Damping Off', 'Little Leaf'],
    marketTrends: 'Consistent demand with good export potential.',
    profitPotential: 'High returns with proper variety selection and pest management.',
    plantingTips: ['Choose disease-resistant varieties', 'Proper staking required', 'Regular harvesting'],
    nutritionalValue: 'Low in calories, good source of fiber and antioxidants',
    storageRequirements: 'Short storage life, immediate marketing preferred',
    processingUses: ['Pickles', 'Dehydrated products', 'Frozen vegetables'],
    yearlyData: [
      { year: 2021, acresPlanted: 145, profitLoss: 16000, averagePrice: 15 },
      { year: 2022, acresPlanted: 155, profitLoss: 18000, averagePrice: 16 },
      { year: 2023, acresPlanted: 160, profitLoss: 20000, averagePrice: 17 },
      { year: 2024, acresPlanted: 165, profitLoss: 22000, averagePrice: 18 },
    ]
  },
  {
    id: '9',
    name: 'Cauliflower (फूल गोभी)',
    scientificName: 'Brassica oleracea',
    category: 'Vegetables',
    profitStatus: 'Moderate',
    latestPrice: 16,
    acresPlanted: 125,
    season: 'Rabi',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 15, max: 20 },
    harvestTime: '3-4 months',
    harvestDays: 90,
    averageYieldPerAcre: 120,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 15, max: 20, optimal: 18 },
      rainfall: { min: 600, max: 900, optimal: 750 },
      humidity: 75,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Aphids', 'Cabbage Butterfly', 'Flea Beetle'],
    commonDiseases: ['Black Rot', 'Club Root', 'Downy Mildew'],
    marketTrends: 'Seasonal demand with good processing opportunities.',
    profitPotential: 'Good returns with proper timing and quality produce.',
    plantingTips: ['Transplant seedlings', 'Ensure adequate moisture', 'Protect from extreme weather'],
    nutritionalValue: 'High in vitamin C, K, and fiber',
    storageRequirements: 'Cool, humid storage for short periods',
    processingUses: ['Frozen vegetables', 'Pickles', 'Dehydrated products'],
    yearlyData: [
      { year: 2021, acresPlanted: 110, profitLoss: 12000, averagePrice: 13 },
      { year: 2022, acresPlanted: 115, profitLoss: 14000, averagePrice: 14 },
      { year: 2023, acresPlanted: 120, profitLoss: 16000, averagePrice: 15 },
      { year: 2024, acresPlanted: 125, profitLoss: 18000, averagePrice: 16 },
    ]
  },
  {
    id: '10',
    name: 'Cabbage (पत्ता गोभी)',
    scientificName: 'Brassica oleracea var. capitata',
    category: 'Vegetables',
    profitStatus: 'Moderate',
    latestPrice: 12,
    acresPlanted: 150,
    season: 'Rabi',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 15, max: 20 },
    harvestTime: '3-4 months',
    harvestDays: 90,
    averageYieldPerAcre: 200,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 15, max: 20, optimal: 18 },
      rainfall: { min: 500, max: 800, optimal: 600 },
      humidity: 80,
      phLevel: { min: 5.0, max: 6.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Cabbage Butterfly', 'Aphids', 'Cutworm'],
    commonDiseases: ['Black Rot', 'Club Root', 'Alternaria Leaf Spot'],
    marketTrends: 'Consistent demand but price fluctuations due to perishable nature.',
    profitPotential: 'Moderate returns with proper marketing and storage.',
    plantingTips: ['Use certified seed potatoes', 'Ensure proper earthing up', 'Regular irrigation'],
    nutritionalValue: 'Good source of carbohydrates, vitamin C, and potassium',
    storageRequirements: 'Cool, dark, well-ventilated storage',
    processingUses: ['Chips', 'French fries', 'Starch', 'Dehydrated products'],
    yearlyData: [
      { year: 2021, acresPlanted: 140, profitLoss: 8000, averagePrice: 10 },
      { year: 2022, acresPlanted: 145, profitLoss: 9000, averagePrice: 11 },
      { year: 2023, acresPlanted: 148, profitLoss: 10000, averagePrice: 11.5 },
      { year: 2024, acresPlanted: 150, profitLoss: 11000, averagePrice: 12 },
    ]
  },
  {
    id: '11',
    name: 'Bottle Gourd (लौकी)',
    scientificName: 'Lagenaria siceraria',
    category: 'Vegetables',
    profitStatus: 'High',
    latestPrice: 14,
    acresPlanted: 95,
    season: 'Kharif',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 20, max: 35 },
    harvestTime: '3-4 months',
    harvestDays: 90,
    averageYieldPerAcre: 150,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 20, max: 35, optimal: 28 },
      rainfall: { min: 600, max: 1200, optimal: 900 },
      humidity: 70,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Fruit Fly', 'Red Pumpkin Beetle', 'Aphids'],
    commonDiseases: ['Downy Mildew', 'Powdery Mildew', 'Mosaic Virus'],
    marketTrends: 'High demand during summer months with good local market.',
    profitPotential: 'Good returns with low input costs and high yield.',
    plantingTips: ['Provide proper support', 'Regular watering', 'Harvest young fruits'],
    nutritionalValue: 'Low in calories, high in water content and fiber',
    storageRequirements: 'Short storage life, immediate consumption preferred',
    processingUses: ['Juice', 'Dehydrated products', 'Traditional medicine'],
    yearlyData: [
      { year: 2021, acresPlanted: 85, profitLoss: 12000, averagePrice: 11 },
      { year: 2022, acresPlanted: 88, profitLoss: 13000, averagePrice: 12 },
      { year: 2023, acresPlanted: 92, profitLoss: 14000, averagePrice: 13 },
      { year: 2024, acresPlanted: 95, profitLoss: 15000, averagePrice: 14 },
    ]
  },
  {
    id: '12',
    name: 'Bitter Gourd (करेला)',
    scientificName: 'Momordica charantia',
    category: 'Vegetables',
    profitStatus: 'High',
    latestPrice: 28,
    acresPlanted: 78,
    season: 'Kharif',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 20, max: 35 },
    harvestTime: '3-4 months',
    harvestDays: 90,
    averageYieldPerAcre: 80,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 20, max: 35, optimal: 28 },
      rainfall: { min: 600, max: 1000, optimal: 800 },
      humidity: 65,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Fruit Fly', 'Aphids', 'Thrips'],
    commonDiseases: ['Downy Mildew', 'Anthracnose', 'Mosaic Virus'],
    marketTrends: 'High demand due to medicinal properties and health consciousness.',
    profitPotential: 'Excellent returns due to premium pricing and health benefits.',
    plantingTips: ['Provide trellises', 'Regular harvesting', 'Disease management important'],
    nutritionalValue: 'Rich in vitamins, minerals, and antioxidants with medicinal properties',
    storageRequirements: 'Cool storage for short periods',
    processingUses: ['Juice', 'Dried powder', 'Health supplements'],
    yearlyData: [
      { year: 2021, acresPlanted: 70, profitLoss: 18000, averagePrice: 24 },
      { year: 2022, acresPlanted: 73, profitLoss: 20000, averagePrice: 26 },
      { year: 2023, acresPlanted: 75, profitLoss: 22000, averagePrice: 27 },
      { year: 2024, acresPlanted: 78, profitLoss: 24000, averagePrice: 28 },
    ]
  },
  {
    id: '13',
    name: 'Okra (भिंडी)',
    scientificName: 'Abelmoschus esculentus',
    category: 'Vegetables',
    profitStatus: 'Moderate',
    latestPrice: 25,
    acresPlanted: 160,
    season: 'Kharif',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 25, max: 35 },
    harvestTime: '2-3 months',
    harvestDays: 60,
    averageYieldPerAcre: 60,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 25, max: 35, optimal: 30 },
      rainfall: { min: 600, max: 1000, optimal: 800 },
      humidity: 65,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Aphids', 'Jassids', 'Shoot and Fruit Borer'],
    commonDiseases: ['Yellow Vein Mosaic', 'Powdery Mildew', 'Fusarium Wilt'],
    marketTrends: 'Steady demand throughout the year with export potential.',
    profitPotential: 'Good returns with quick harvest and continuous picking.',
    plantingTips: ['Choose virus-resistant varieties', 'Regular picking', 'Proper spacing'],
    nutritionalValue: 'Rich in fiber, vitamin C, K, and folate',
    storageRequirements: 'Short storage life, immediate marketing preferred',
    processingUses: ['Dehydrated products', 'Frozen vegetables', 'Pickles'],
    yearlyData: [
      { year: 2021, acresPlanted: 145, profitLoss: 12000, averagePrice: 20 },
      { year: 2022, acresPlanted: 150, profitLoss: 14000, averagePrice: 22 },
      { year: 2023, acresPlanted: 155, profitLoss: 16000, averagePrice: 24 },
      { year: 2024, acresPlanted: 160, profitLoss: 18000, averagePrice: 25 },
    ]
  },
  {
    id: '14',
    name: 'Carrot (गाजर)',
    scientificName: 'Daucus carota',
    category: 'Vegetables',
    profitStatus: 'High',
    latestPrice: 20,
    acresPlanted: 110,
    season: 'Rabi',
    idealSoilType: 'Sandy',
    idealTempRange: { min: 16, max: 20 },
    harvestTime: '3-4 months',
    harvestDays: 90,
    averageYieldPerAcre: 200,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 16, max: 20, optimal: 18 },
      rainfall: { min: 600, max: 900, optimal: 750 },
      humidity: 70,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Low',
    commonPests: ['Aphids', 'Carrot Fly', 'Nematodes'],
    commonDiseases: ['Leaf Blight', 'Black Rot', 'Cavity Spot'],
    marketTrends: 'High demand for fresh consumption and processing industry.',
    profitPotential: 'Excellent returns with good storage and value addition.',
    plantingTips: ['Deep tillage required', 'Avoid fresh manure', 'Proper thinning'],
    nutritionalValue: 'Rich in beta-carotene, vitamin A, and fiber',
    storageRequirements: 'Cool, humid storage for extended periods',
    processingUses: ['Juice', 'Baby food', 'Dehydrated products', 'Pickles'],
    yearlyData: [
      { year: 2021, acresPlanted: 95, profitLoss: 16000, averagePrice: 17 },
      { year: 2022, acresPlanted: 100, profitLoss: 18000, averagePrice: 18 },
      { year: 2023, acresPlanted: 105, profitLoss: 20000, averagePrice: 19 },
      { year: 2024, acresPlanted: 110, profitLoss: 22000, averagePrice: 20 },
    ]
  },
  {
    id: '15',
    name: 'Green Peas (हरी मटर)',
    scientificName: 'Pisum sativum',
    category: 'Vegetables',
    profitStatus: 'High',
    latestPrice: 35,
    acresPlanted: 220,
    season: 'Rabi',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 12, max: 22 },
    harvestTime: '3-4 months',
    harvestDays: 90,
    averageYieldPerAcre: 60,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 12, max: 22, optimal: 18 },
      rainfall: { min: 600, max: 900, optimal: 750 },
      humidity: 75,
      phLevel: { min: 6.0, max: 7.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Aphids', 'Pod Borer', 'Thrips'],
    commonDiseases: ['Powdery Mildew', 'Rust', 'Wilt'],
    marketTrends: 'High demand from processing industry and fresh market.',
    profitPotential: 'Excellent returns with quick harvest cycle and multiple uses.',
    plantingTips: ['Inoculate seeds with rhizobium', 'Provide support', 'Timely harvesting'],
    nutritionalValue: 'High in protein, vitamins, and minerals',
    storageRequirements: 'Cool storage for fresh peas, processing extends shelf life',
    processingUses: ['Frozen peas', 'Canned peas', 'Dehydrated products'],
    yearlyData: [
      { year: 2021, acresPlanted: 200, profitLoss: 20000, averagePrice: 30 },
      { year: 2022, acresPlanted: 210, profitLoss: 24000, averagePrice: 32 },
      { year: 2023, acresPlanted: 215, profitLoss: 28000, averagePrice: 34 },
      { year: 2024, acresPlanted: 220, profitLoss: 32000, averagePrice: 35 },
    ]
  },
  {
    id: '16',
    name: 'Spinach (पालक)',
    scientificName: 'Spinacia oleracea',
    category: 'Vegetables',
    profitStatus: 'High',
    latestPrice: 30,
    acresPlanted: 85,
    season: 'Rabi',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 15, max: 20 },
    harvestTime: '1-2 months',
    harvestDays: 45,
    averageYieldPerAcre: 80,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 15, max: 20, optimal: 18 },
      rainfall: { min: 400, max: 700, optimal: 550 },
      humidity: 80,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Low',
    commonPests: ['Aphids', 'Leaf Miner', 'Cutworm'],
    commonDiseases: ['Downy Mildew', 'White Rust', 'Damping Off'],
    marketTrends: 'High demand for nutritious leafy vegetables and health foods.',
    profitPotential: 'Excellent returns with quick harvest and high nutritional value.',
    plantingTips: ['Successive sowings', 'Adequate moisture', 'Regular harvesting'],
    nutritionalValue: 'Rich in iron, vitamins A, C, K, and folate',
    storageRequirements: 'Very short storage life, immediate consumption',
    processingUses: ['Frozen vegetables', 'Dehydrated powder', 'Health supplements'],
    yearlyData: [
      { year: 2021, acresPlanted: 75, profitLoss: 18000, averagePrice: 25 },
      { year: 2022, acresPlanted: 78, profitLoss: 20000, averagePrice: 27 },
      { year: 2023, acresPlanted: 82, profitLoss: 24000, averagePrice: 29 },
      { year: 2024, acresPlanted: 85, profitLoss: 28000, averagePrice: 30 },
    ]
  },

  // FRUITS
  {
    id: '17',
    name: 'Mango (आम)',
    scientificName: 'Mangifera indica',
    category: 'Fruits',
    profitStatus: 'High',
    latestPrice: 45,
    acresPlanted: 180,
    season: 'Year-round',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 24, max: 30 },
    harvestTime: '3-5 years (first harvest)',
    harvestDays: 1095,
    averageYieldPerAcre: 80,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 24, max: 30, optimal: 27 },
      rainfall: { min: 750, max: 2500, optimal: 1200 },
      humidity: 75,
      phLevel: { min: 5.5, max: 7.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Fruit Fly', 'Mango Hopper', 'Scale Insects'],
    commonDiseases: ['Anthracnose', 'Powdery Mildew', 'Die Back'],
    marketTrends: 'High export demand, premium varieties fetch better prices.',
    profitPotential: 'Excellent long-term returns with premium varieties.',
    plantingTips: ['Choose quality grafted plants', 'Proper spacing', 'Regular pruning'],
    nutritionalValue: 'Rich in vitamin A, C, and dietary fiber',
    storageRequirements: 'Cool storage for fresh fruit, processing extends shelf life',
    processingUses: ['Pulp', 'Juice', 'Pickles', 'Dried mango'],
    yearlyData: [
      { year: 2021, acresPlanted: 160, profitLoss: 35000, averagePrice: 38 },
      { year: 2022, acresPlanted: 170, profitLoss: 40000, averagePrice: 41 },
      { year: 2023, acresPlanted: 175, profitLoss: 42000, averagePrice: 43 },
      { year: 2024, acresPlanted: 180, profitLoss: 45000, averagePrice: 45 },
    ]
  },
  {
    id: '18',
    name: 'Banana (केला)',
    scientificName: 'Musa paradisiaca',
    category: 'Fruits',
    profitStatus: 'High',
    latestPrice: 20,
    acresPlanted: 220,
    season: 'Year-round',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 26, max: 30 },
    harvestTime: '11-15 months',
    harvestDays: 365,
    averageYieldPerAcre: 400,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 26, max: 30, optimal: 28 },
      rainfall: { min: 1200, max: 2500, optimal: 2000 },
      humidity: 85,
      phLevel: { min: 6.0, max: 7.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Nematodes', 'Weevil', 'Aphids'],
    commonDiseases: ['Panama Disease', 'Black Sigatoka', 'Bunchy Top'],
    marketTrends: 'Steady demand, good export potential for quality varieties.',
    profitPotential: 'Good returns with year-round production possible.',
    plantingTips: ['Use tissue culture plants', 'Proper drainage', 'Wind protection'],
    nutritionalValue: 'Rich in potassium, vitamin B6, and carbohydrates',
    storageRequirements: 'Controlled atmosphere storage for export',
    processingUses: ['Chips', 'Powder', 'Baby food', 'Fiber'],
    yearlyData: [
      { year: 2021, acresPlanted: 200, profitLoss: 25000, averagePrice: 17 },
      { year: 2022, acresPlanted: 210, profitLoss: 28000, averagePrice: 18 },
      { year: 2023, acresPlanted: 215, profitLoss: 30000, averagePrice: 19 },
      { year: 2024, acresPlanted: 220, profitLoss: 32000, averagePrice: 20 },
    ]
  },
  {
    id: '19',
    name: 'Guava (अमरूद)',
    scientificName: 'Psidium guajava',
    category: 'Fruits',
    profitStatus: 'High',
    latestPrice: 25,
    acresPlanted: 145,
    season: 'Year-round',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 23, max: 28 },
    harvestTime: '2-4 years (first harvest)',
    harvestDays: 730,
    averageYieldPerAcre: 120,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 23, max: 28, optimal: 25 },
      rainfall: { min: 800, max: 1500, optimal: 1000 },
      humidity: 70,
      phLevel: { min: 6.0, max: 7.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Fruit Fly', 'Scale Insects', 'Mealy Bugs'],
    commonDiseases: ['Anthracnose', 'Canker', 'Wilt'],
    marketTrends: 'High demand for fresh consumption and processing.',
    profitPotential: 'Excellent returns with processing opportunities.',
    plantingTips: ['Choose grafted plants', 'Regular pruning', 'Pest management'],
    nutritionalValue: 'Extremely rich in vitamin C, fiber, and antioxidants',
    storageRequirements: 'Cool storage for fresh fruit',
    processingUses: ['Juice', 'Jelly', 'Pulp', 'Nectar'],
    yearlyData: [
      { year: 2021, acresPlanted: 125, profitLoss: 22000, averagePrice: 20 },
      { year: 2022, acresPlanted: 135, profitLoss: 26000, averagePrice: 22 },
      { year: 2023, acresPlanted: 140, profitLoss: 30000, averagePrice: 24 },
      { year: 2024, acresPlanted: 145, profitLoss: 35000, averagePrice: 25 },
    ]
  },
  {
    id: '20',
    name: 'Papaya (पपीता)',
    scientificName: 'Carica papaya',
    category: 'Fruits',
    profitStatus: 'High',
    latestPrice: 15,
    acresPlanted: 85,
    season: 'Year-round',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 20, max: 33 },
    harvestTime: '10-12 months',
    harvestDays: 300,
    averageYieldPerAcre: 300,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 20, max: 33, optimal: 28 },
      rainfall: { min: 1000, max: 1500, optimal: 1200 },
      humidity: 75,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Aphids', 'Mites', 'Fruit Fly'],
    commonDiseases: ['Papaya Ring Spot Virus', 'Anthracnose', 'Damping Off'],
    marketTrends: 'Growing demand for fresh fruit and health products.',
    profitPotential: 'Good returns with quick production and high yield.',
    plantingTips: ['Choose virus-resistant varieties', 'Proper drainage', 'Regular harvesting'],
    nutritionalValue: 'Rich in vitamin C, A, and digestive enzymes',
    storageRequirements: 'Cool storage for ripe fruit',
    processingUses: ['Juice', 'Pulp', 'Papain enzyme', 'Dried fruit'],
    yearlyData: [
      { year: 2021, acresPlanted: 75, profitLoss: 15000, averagePrice: 12 },
      { year: 2022, acresPlanted: 78, profitLoss: 17000, averagePrice: 13 },
      { year: 2023, acresPlanted: 82, profitLoss: 19000, averagePrice: 14 },
      { year: 2024, acresPlanted: 85, profitLoss: 22000, averagePrice: 15 },
    ]
  },
  {
    id: '21',
    name: 'Pomegranate (अनार)',
    scientificName: 'Punica granatum',
    category: 'Fruits',
    profitStatus: 'High',
    latestPrice: 80,
    acresPlanted: 65,
    season: 'Year-round',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 15, max: 35 },
    harvestTime: '3-4 years (first harvest)',
    harvestDays: 1095,
    averageYieldPerAcre: 60,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 15, max: 35, optimal: 25 },
      rainfall: { min: 500, max: 800, optimal: 650 },
      humidity: 60,
      phLevel: { min: 6.5, max: 7.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Aphids', 'Fruit Borer', 'Thrips'],
    commonDiseases: ['Bacterial Blight', 'Anthracnose', 'Wilt'],
    marketTrends: 'Premium fruit with excellent export potential and health benefits.',
    profitPotential: 'Exceptional returns due to high value and medicinal properties.',
    plantingTips: ['Choose quality grafted plants', 'Drip irrigation preferred', 'Regular pruning'],
    nutritionalValue: 'Rich in antioxidants, vitamin C, and anti-inflammatory compounds',
    storageRequirements: 'Cool, dry storage for extended periods',
    processingUses: ['Juice', 'Extract', 'Dried seeds', 'Health supplements'],
    yearlyData: [
      { year: 2021, acresPlanted: 55, profitLoss: 45000, averagePrice: 65 },
      { year: 2022, acresPlanted: 58, profitLoss: 52000, averagePrice: 70 },
      { year: 2023, acresPlanted: 62, profitLoss: 60000, averagePrice: 75 },
      { year: 2024, acresPlanted: 65, profitLoss: 68000, averagePrice: 80 },
    ]
  },
  {
    id: '22',
    name: 'Grapes (अंगूर)',
    scientificName: 'Vitis vinifera',
    category: 'Fruits',
    profitStatus: 'High',
    latestPrice: 60,
    acresPlanted: 95,
    season: 'Year-round',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 15, max: 40 },
    harvestTime: '3-4 years (first harvest)',
    harvestDays: 1095,
    averageYieldPerAcre: 150,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 15, max: 40, optimal: 28 },
      rainfall: { min: 600, max: 1200, optimal: 900 },
      humidity: 65,
      phLevel: { min: 6.0, max: 8.0 }
    },
    pestDiseaseRisk: 'High',
    commonPests: ['Thrips', 'Mealybugs', 'Flea Beetle'],
    commonDiseases: ['Downy Mildew', 'Powdery Mildew', 'Anthracnose'],
    marketTrends: 'Premium fruit with excellent export potential.',
    profitPotential: 'Excellent returns with proper variety selection and management.',
    plantingTips: ['Choose disease-resistant varieties', 'Proper trellising', 'Pruning essential'],
    nutritionalValue: 'Rich in antioxidants, vitamin C, and natural sugars',
    storageRequirements: 'Cold storage for extended shelf life',
    processingUses: ['Wine', 'Juice', 'Raisins', 'Jam'],
    yearlyData: [
      { year: 2021, acresPlanted: 85, profitLoss: 55000, averagePrice: 50 },
      { year: 2022, acresPlanted: 88, profitLoss: 62000, averagePrice: 53 },
      { year: 2023, acresPlanted: 92, profitLoss: 68000, averagePrice: 57 },
      { year: 2024, acresPlanted: 95, profitLoss: 75000, averagePrice: 60 },
    ]
  },
  {
    id: '23',
    name: 'Watermelon (तरबूज)',
    scientificName: 'Citrullus lanatus',
    category: 'Fruits',
    profitStatus: 'High',
    latestPrice: 8,
    acresPlanted: 125,
    season: 'Zaid',
    idealSoilType: 'Sandy',
    idealTempRange: { min: 20, max: 35 },
    harvestTime: '3-4 months',
    harvestDays: 90,
    averageYieldPerAcre: 300,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 20, max: 35, optimal: 28 },
      rainfall: { min: 400, max: 800, optimal: 600 },
      humidity: 60,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Aphids', 'Red Pumpkin Beetle', 'Fruit Fly'],
    commonDiseases: ['Fusarium Wilt', 'Anthracnose', 'Downy Mildew'],
    marketTrends: 'High demand during summer months with good profit margins.',
    profitPotential: 'Excellent returns with high yield and seasonal demand.',
    plantingTips: ['Proper spacing required', 'Mulching beneficial', 'Regular watering'],
    nutritionalValue: 'High water content, vitamin A, C, and lycopene',
    storageRequirements: 'Short storage life, immediate marketing preferred',
    processingUses: ['Juice', 'Seeds for oil', 'Pickles from rind'],
    yearlyData: [
      { year: 2021, acresPlanted: 110, profitLoss: 20000, averagePrice: 6 },
      { year: 2022, acresPlanted: 115, profitLoss: 22000, averagePrice: 6.5 },
      { year: 2023, acresPlanted: 120, profitLoss: 25000, averagePrice: 7.5 },
      { year: 2024, acresPlanted: 125, profitLoss: 28000, averagePrice: 8 },
    ]
  },
  {
    id: '24',
    name: 'Orange (संतरा)',
    scientificName: 'Citrus sinensis',
    category: 'Fruits',
    profitStatus: 'High',
    latestPrice: 35,
    acresPlanted: 110,
    season: 'Year-round',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 15, max: 30 },
    harvestTime: '3-5 years (first harvest)',
    harvestDays: 1095,
    averageYieldPerAcre: 100,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 15, max: 30, optimal: 25 },
      rainfall: { min: 1000, max: 1500, optimal: 1200 },
      humidity: 70,
      phLevel: { min: 6.0, max: 7.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Citrus Psylla', 'Scale Insects', 'Aphids'],
    commonDiseases: ['Canker', 'Greening Disease', 'Gummosis'],
    marketTrends: 'High demand for fresh consumption and juice industry.',
    profitPotential: 'Good returns with processing opportunities.',
    plantingTips: ['Choose disease-free rootstock', 'Proper spacing', 'Regular pruning'],
    nutritionalValue: 'Excellent source of vitamin C, fiber, and folate',
    storageRequirements: 'Cool storage for extended shelf life',
    processingUses: ['Juice', 'Concentrate', 'Essential oils', 'Pectin'],
    yearlyData: [
      { year: 2021, acresPlanted: 95, profitLoss: 28000, averagePrice: 28 },
      { year: 2022, acresPlanted: 100, profitLoss: 32000, averagePrice: 30 },
      { year: 2023, acresPlanted: 105, profitLoss: 36000, averagePrice: 33 },
      { year: 2024, acresPlanted: 110, profitLoss: 40000, averagePrice: 35 },
    ]
  },

  // FLOWERS
  {
    id: '25',
    name: 'Marigold (गेंदा)',
    scientificName: 'Tagetes erecta',
    category: 'Flowers',
    profitStatus: 'High',
    latestPrice: 12,
    acresPlanted: 85,
    season: 'Year-round',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 18, max: 25 },
    harvestTime: '2-3 months',
    harvestDays: 70,
    averageYieldPerAcre: 60,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 18, max: 25, optimal: 22 },
      rainfall: { min: 600, max: 1000, optimal: 800 },
      humidity: 65,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Low',
    commonPests: ['Aphids', 'Red Spider Mite', 'Caterpillars'],
    commonDiseases: ['Leaf Spot', 'Root Rot', 'Damping Off'],
    marketTrends: 'High demand for religious ceremonies and festivals.',
    profitPotential: 'Good returns with multiple harvests per year.',
    plantingTips: ['Start with seedlings', 'Regular watering', 'Pinch growing tips'],
    nutritionalValue: 'Contains lutein and other beneficial compounds',
    storageRequirements: 'Fresh flowers need immediate marketing',
    processingUses: ['Essential oil', 'Natural dye', 'Medicinal extracts'],
    yearlyData: [
      { year: 2021, acresPlanted: 75, profitLoss: 8000, averagePrice: 9 },
      { year: 2022, acresPlanted: 80, profitLoss: 9000, averagePrice: 10 },
      { year: 2023, acresPlanted: 82, profitLoss: 10000, averagePrice: 11 },
      { year: 2024, acresPlanted: 85, profitLoss: 12000, averagePrice: 12 },
    ]
  },
  {
    id: '26',
    name: 'Jasmine (चमेली)',
    scientificName: 'Jasminum sambac',
    category: 'Flowers',
    profitStatus: 'High',
    latestPrice: 150,
    acresPlanted: 45,
    season: 'Year-round',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 20, max: 30 },
    harvestTime: '1-2 years (first harvest)',
    harvestDays: 365,
    averageYieldPerAcre: 15,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 20, max: 30, optimal: 25 },
      rainfall: { min: 1000, max: 1500, optimal: 1200 },
      humidity: 75,
      phLevel: { min: 6.0, max: 7.5 }
    },
    pestDiseaseRisk: 'Low',
    commonPests: ['Scale Insects', 'Aphids', 'Caterpillars'],
    commonDiseases: ['Leaf Spot', 'Root Rot', 'Powdery Mildew'],
    marketTrends: 'Premium flower with high demand for perfume and religious use.',
    profitPotential: 'Excellent returns due to high value and year-round demand.',
    plantingTips: ['Choose healthy cuttings', 'Provide support', 'Regular harvesting'],
    nutritionalValue: 'Used for aromatherapy and traditional medicine',
    storageRequirements: 'Immediate processing or marketing required',
    processingUses: ['Essential oil', 'Perfume', 'Tea', 'Garlands'],
    yearlyData: [
      { year: 2021, acresPlanted: 40, profitLoss: 45000, averagePrice: 120 },
      { year: 2022, acresPlanted: 42, profitLoss: 52000, averagePrice: 130 },
      { year: 2023, acresPlanted: 43, profitLoss: 58000, averagePrice: 140 },
      { year: 2024, acresPlanted: 45, profitLoss: 65000, averagePrice: 150 },
    ]
  },
  {
    id: '27',
    name: 'Rose (गुलाब)',
    scientificName: 'Rosa damascena',
    category: 'Flowers',
    profitStatus: 'High',
    latestPrice: 80,
    acresPlanted: 65,
    season: 'Rabi',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 15, max: 25 },
    harvestTime: '1-2 years (first harvest)',
    harvestDays: 365,
    averageYieldPerAcre: 25,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 15, max: 25, optimal: 20 },
      rainfall: { min: 600, max: 1000, optimal: 800 },
      humidity: 70,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Aphids', 'Thrips', 'Rose Chafer'],
    commonDiseases: ['Black Spot', 'Powdery Mildew', 'Rust'],
    marketTrends: 'High value flower with excellent processing opportunities.',
    profitPotential: 'Excellent returns with essential oil and cosmetic uses.',
    plantingTips: ['Choose disease-resistant varieties', 'Proper pruning', 'Adequate spacing'],
    nutritionalValue: 'Rich in vitamin C and antioxidants',
    storageRequirements: 'Cool storage for fresh flowers',
    processingUses: ['Rose water', 'Essential oil', 'Gulkand', 'Perfume'],
    yearlyData: [
      { year: 2021, acresPlanted: 55, profitLoss: 35000, averagePrice: 65 },
      { year: 2022, acresPlanted: 58, profitLoss: 40000, averagePrice: 70 },
      { year: 2023, acresPlanted: 62, profitLoss: 45000, averagePrice: 75 },
      { year: 2024, acresPlanted: 65, profitLoss: 52000, averagePrice: 80 },
    ]
  },
  {
    id: '28',
    name: 'Chrysanthemum (गुलदाउदी)',
    scientificName: 'Chrysanthemum morifolium',
    category: 'Flowers',
    profitStatus: 'Moderate',
    latestPrice: 20,
    acresPlanted: 55,
    season: 'Rabi',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 15, max: 25 },
    harvestTime: '3-4 months',
    harvestDays: 100,
    averageYieldPerAcre: 45,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 15, max: 25, optimal: 20 },
      rainfall: { min: 600, max: 900, optimal: 750 },
      humidity: 70,
      phLevel: { min: 6.0, max: 7.0 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Aphids', 'Leaf Miner', 'Thrips'],
    commonDiseases: ['Leaf Spot', 'Powdery Mildew', 'Wilt'],
    marketTrends: 'Good demand for cut flowers and decorative purposes.',
    profitPotential: 'Moderate returns with seasonal demand peaks.',
    plantingTips: ['Use rooted cuttings', 'Provide support', 'Day length control'],
    nutritionalValue: 'Used in traditional medicine and tea',
    storageRequirements: 'Cool storage for cut flowers',
    processingUses: ['Cut flowers', 'Dried flowers', 'Tea', 'Natural pesticide'],
    yearlyData: [
      { year: 2021, acresPlanted: 45, profitLoss: 12000, averagePrice: 16 },
      { year: 2022, acresPlanted: 48, profitLoss: 14000, averagePrice: 17 },
      { year: 2023, acresPlanted: 52, profitLoss: 16000, averagePrice: 19 },
      { year: 2024, acresPlanted: 55, profitLoss: 18000, averagePrice: 20 },
    ]
  },
  {
    id: '29',
    name: 'Tuberose (रजनीगंधा)',
    scientificName: 'Polianthes tuberosa',
    category: 'Flowers',
    profitStatus: 'High',
    latestPrice: 100,
    acresPlanted: 35,
    season: 'Year-round',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 20, max: 30 },
    harvestTime: '6-8 months',
    harvestDays: 210,
    averageYieldPerAcre: 20,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 20, max: 30, optimal: 25 },
      rainfall: { min: 800, max: 1200, optimal: 1000 },
      humidity: 75,
      phLevel: { min: 6.5, max: 7.5 }
    },
    pestDiseaseRisk: 'Low',
    commonPests: ['Aphids', 'Thrips', 'Nematodes'],
    commonDiseases: ['Leaf Spot', 'Bulb Rot', 'Mosaic Virus'],
    marketTrends: 'Premium flower with excellent fragrance value.',
    profitPotential: 'Excellent returns due to high value and perfume industry demand.',
    plantingTips: ['Plant quality bulbs', 'Proper spacing', 'Good drainage essential'],
    nutritionalValue: 'Used in aromatherapy and perfumery',
    storageRequirements: 'Cool storage for fresh flowers',
    processingUses: ['Essential oil', 'Perfume', 'Garlands', 'Concrete'],
    yearlyData: [
      { year: 2021, acresPlanted: 30, profitLoss: 25000, averagePrice: 80 },
      { year: 2022, acresPlanted: 32, profitLoss: 28000, averagePrice: 85 },
      { year: 2023, acresPlanted: 33, profitLoss: 32000, averagePrice: 95 },
      { year: 2024, acresPlanted: 35, profitLoss: 38000, averagePrice: 100 },
    ]
  },

  // SPICES
  {
    id: '30',
    name: 'Turmeric (हल्दी)',
    scientificName: 'Curcuma longa',
    category: 'Spices',
    profitStatus: 'High',
    latestPrice: 85,
    acresPlanted: 180,
    season: 'Kharif',
    idealSoilType: 'Loamy',
    idealTempRange: { min: 20, max: 30 },
    harvestTime: '8-10 months',
    harvestDays: 270,
    averageYieldPerAcre: 25,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 20, max: 30, optimal: 25 },
      rainfall: { min: 1000, max: 1500, optimal: 1200 },
      humidity: 75,
      phLevel: { min: 5.0, max: 7.5 }
    },
    pestDiseaseRisk: 'Low',
    commonPests: ['Shoot Borer', 'Scale Insects', 'Rhizome Fly'],
    commonDiseases: ['Leaf Blotch', 'Rhizome Rot', 'Leaf Spot'],
    marketTrends: 'Strong export demand and domestic spice market growth.',
    profitPotential: 'Excellent returns due to medicinal and culinary uses worldwide.',
    plantingTips: ['Use quality rhizomes', 'Proper bed preparation', 'Organic manure application'],
    nutritionalValue: 'Rich in curcumin, antioxidants, and anti-inflammatory compounds',
    storageRequirements: 'Dry storage after proper curing',
    processingUses: ['Powder', 'Extract', 'Oleoresin', 'Medicinal products'],
    yearlyData: [
      { year: 2021, acresPlanted: 160, profitLoss: 35000, averagePrice: 75 },
      { year: 2022, acresPlanted: 170, profitLoss: 40000, averagePrice: 80 },
      { year: 2023, acresPlanted: 175, profitLoss: 45000, averagePrice: 82 },
      { year: 2024, acresPlanted: 180, profitLoss: 50000, averagePrice: 85 },
    ]
  },
  {
    id: '31',
    name: 'Cumin (जीरा)',
    scientificName: 'Cuminum cyminum',
    category: 'Spices',
    profitStatus: 'High',
    latestPrice: 450,
    acresPlanted: 95,
    season: 'Rabi',
    idealSoilType: 'Sandy',
    idealTempRange: { min: 10, max: 25 },
    harvestTime: '4-5 months',
    harvestDays: 120,
    averageYieldPerAcre: 4,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 10, max: 25, optimal: 20 },
      rainfall: { min: 300, max: 600, optimal: 400 },
      humidity: 60,
      phLevel: { min: 6.8, max: 8.3 }
    },
    pestDiseaseRisk: 'Low',
    commonPests: ['Aphids', 'Cumin Borer', 'Thrips'],
    commonDiseases: ['Wilt', 'Blight', 'Powdery Mildew'],
    marketTrends: 'Premium export market with strong domestic spice demand.',
    profitPotential: 'Exceptional returns due to high value spice with global demand.',
    plantingTips: ['Use certified seeds', 'Sow at right time', 'Avoid waterlogging'],
    nutritionalValue: 'Rich in iron, antioxidants, and essential oils',
    storageRequirements: 'Dry storage in airtight containers',
    processingUses: ['Whole spice', 'Powder', 'Oil extraction', 'Medicinal use'],
    yearlyData: [
      { year: 2021, acresPlanted: 85, profitLoss: 85000, averagePrice: 380 },
      { year: 2022, acresPlanted: 90, profitLoss: 95000, averagePrice: 410 },
      { year: 2023, acresPlanted: 92, profitLoss: 105000, averagePrice: 430 },
      { year: 2024, acresPlanted: 95, profitLoss: 115000, averagePrice: 450 },
    ]
  },

  // OILSEEDS
  {
    id: '32',
    name: 'Soybean (सोयाबीन)',
    scientificName: 'Glycine max',
    category: 'Oilseeds',
    profitStatus: 'High',
    latestPrice: 42,
    acresPlanted: 890,
    season: 'Kharif',
    idealSoilType: 'Well-drained',
    idealTempRange: { min: 20, max: 30 },
    harvestTime: '3-4 months',
    harvestDays: 95,
    averageYieldPerAcre: 12,
    yieldUnit: 'quintals',
    requirements: {
      temperature: { min: 20, max: 30, optimal: 25 },
      rainfall: { min: 500, max: 1200, optimal: 800 },
      humidity: 70,
      phLevel: { min: 6.0, max: 7.5 }
    },
    pestDiseaseRisk: 'Medium',
    commonPests: ['Stem Fly', 'Pod Borer', 'Leaf Eater'],
    commonDiseases: ['Rust', 'Bacterial Blight', 'Root Rot'],
    marketTrends: 'Strong export demand and growing domestic consumption for oil and protein.',
    profitPotential: 'Excellent returns due to multiple uses - oil, meal, and protein foods.',
    plantingTips: ['Use rhizobium inoculated seeds', 'Maintain plant population', 'Timely harvesting'],
    nutritionalValue: 'High protein content, essential amino acids, and healthy oils',
    storageRequirements: 'Dry storage with proper ventilation',
    processingUses: ['Oil extraction', 'Soy meal', 'Tofu', 'Soy milk'],
    yearlyData: [
      { year: 2021, acresPlanted: 820, profitLoss: 22000, averagePrice: 38 },
      { year: 2022, acresPlanted: 850, profitLoss: 26000, averagePrice: 40 },
      { year: 2023, acresPlanted: 870, profitLoss: 30000, averagePrice: 41 },
      { year: 2024, acresPlanted: 890, profitLoss: 35000, averagePrice: 42 },
    ]
  }
];

export const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

export const SEASONS = ['Kharif', 'Rabi', 'Zaid', 'Year-round'] as const;

export const CROP_CATEGORIES = [
  'Grains & Pulses',
  'Vegetables', 
  'Fruits',
  'Spices',
  'Flowers',
  'Herbs & Plantation',
  'Oilseeds'
] as const;
